import type { Pose, StyleTab, PoseCategory } from '../../lib/punk-ai/types';

export interface PunkPose extends Pose {
  styles: StyleTab[];
  category: PoseCategory;
  difficulty: 'easy' | 'medium' | 'hard';
  comfort: 'comfortable' | 'moderate' | 'strenuous';
  engagement: number;
  tags: string[];
}

const bj = () => [
  { name: 'head', x: 0, y: 0.8, z: 0 },
  { name: 'neck', x: 0, y: 0.7, z: 0 },
  { name: 'leftShoulder', x: -0.15, y: 0.68, z: 0 },
  { name: 'rightShoulder', x: 0.15, y: 0.68, z: 0 },
  { name: 'leftElbow', x: -0.2, y: 0.55, z: 0 },
  { name: 'rightElbow', x: 0.2, y: 0.55, z: 0 },
  { name: 'leftHand', x: -0.22, y: 0.4, z: 0 },
  { name: 'rightHand', x: 0.22, y: 0.4, z: 0 },
  { name: 'spine', x: 0, y: 0.55, z: 0 },
  { name: 'hip', x: 0, y: 0.4, z: 0 },
  { name: 'leftHip', x: -0.1, y: 0.4, z: 0 },
  { name: 'rightHip', x: 0.1, y: 0.4, z: 0 },
  { name: 'leftKnee', x: -0.08, y: 0.22, z: 0 },
  { name: 'rightKnee', x: 0.08, y: 0.22, z: 0 },
  { name: 'leftFoot', x: -0.08, y: 0.0, z: 0 },
  { name: 'rightFoot', x: 0.08, y: 0.0, z: 0 },
];

export const ALL_POSES: PunkPose[] = [
  // 1. PORTRAIT POSES
  { id: 'classic_portrait', name: 'Classic Portrait', category: 'portrait', description: 'Face slightly angled, soft shoulders, natural lighting', difficulty: 'easy', comfort: 'comfortable', engagement: 88, styles: ['Aesthetic', 'Natural', 'Minimal', 'Bright', 'PinterestTrend'], tags: ['classic', 'timeless', 'soft'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'nature', 'urban'], angles: ['eye_level'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.03, y: 0.8, z: -0.05 } : i === 6 ? { ...j, x: -0.18, y: 0.35 } : i === 14 ? { ...j, x: -0.04 } : j) },
  { id: 'three_quarter', name: 'Three-Quarter Turn', category: 'portrait', description: 'Body turned 45°, face toward camera', difficulty: 'easy', comfort: 'comfortable', engagement: 85, styles: ['Natural', 'Aesthetic', 'Editorial', 'Vintage'], tags: ['flattering', 'slimming', 'classic'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'urban', 'nature'], angles: ['eye_level'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.08, y: 0.8, z: -0.08 } : i === 2 ? { ...j, x: -0.2 } : i === 3 ? { ...j, x: 0.1 } : i === 14 ? { ...j, x: -0.06 } : i === 15 ? { ...j, x: 0.1 } : j) },

  // 2. TRAVEL POSES
  { id: 'wanderlust_gaze', name: 'Wanderlust Gaze', category: 'travel', description: 'Looking into distance, arms relaxed, walking stance', difficulty: 'easy', comfort: 'comfortable', engagement: 92, styles: ['Travel', 'Natural', 'Adventure', 'Aesthetic', 'InstagramTrend'], tags: ['wanderlust', 'exploring', 'destination'], genders: ['male', 'female', 'neutral'], scenes: ['nature', 'mountain', 'beach', 'street'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.05, y: 0.8, z: -0.12 } : i === 14 ? { ...j, x: -0.04, y: 0 } : i === 15 ? { ...j, x: 0.1, y: 0 } : i === 6 ? { ...j, x: -0.2, y: 0.32 } : j) },
  { id: 'map_reader', name: 'Map Reader', category: 'travel', description: 'Holding map or phone, looking down, casual explorer', difficulty: 'easy', comfort: 'comfortable', engagement: 78, styles: ['Travel', 'Cute', 'Natural', 'Lifestyle'], tags: ['exploring', 'candid', 'urban'], genders: ['male', 'female', 'neutral'], scenes: ['urban', 'street'], angles: ['high_angle', 'eye_level'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0, y: 0.75, z: 0.05 } : i === 6 ? { ...j, x: -0.15, y: 0.3, z: 0.08 } : i === 7 ? { ...j, x: 0.1, y: 0.35, z: 0.05 } : j) },

  // 3. FASHION POSES
  { id: 'editorial_stand', name: 'Editorial Stand', category: 'fashion', description: 'High fashion confident stance, one hand on hip', difficulty: 'medium', comfort: 'moderate', engagement: 90, styles: ['Fashion', 'Editorial', 'Luxury', 'Aesthetic', 'PinterestTrend'], tags: ['editorial', 'high_fashion', 'confident'], genders: ['female', 'neutral'], scenes: ['urban', 'architecture', 'indoor'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: -0.02, y: 0.82, z: -0.03 } : i === 4 ? { ...j, x: -0.12, y: 0.52, z: 0.08 } : i === 5 ? { ...j, x: 0.18, y: 0.5, z: 0.05 } : i === 6 ? { ...j, x: -0.12, y: 0.38, z: 0.1 } : i === 14 ? { ...j, x: -0.06 } : i === 15 ? { ...j, x: 0.12 } : j) },
  { id: 'fashion_walk', name: 'Fashion Walk', category: 'fashion', description: 'Dynamic walking pose, confident stride', difficulty: 'medium', comfort: 'moderate', engagement: 87, styles: ['Fashion', 'Street', 'Editorial', 'Viral'], tags: ['runway', 'stride', 'dynamic'], genders: ['male', 'female', 'neutral'], scenes: ['urban', 'street', 'architecture'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 12 ? { ...j, x: -0.15, y: 0.18, z: 0.1 } : i === 13 ? { ...j, x: 0.15, y: 0.22, z: -0.08 } : i === 14 ? { ...j, x: -0.15, y: 0, z: 0.15 } : i === 15 ? { ...j, x: 0.15, y: 0, z: -0.12 } : i === 6 ? { ...j, x: -0.25, y: 0.32 } : i === 7 ? { ...j, x: 0.22, y: 0.35 } : j) },

  // 4. LUXURY POSES
  { id: 'luxury_profile', name: 'Luxury Profile', category: 'luxury', description: 'Side profile, refined posture, minimalist backdrop', difficulty: 'medium', comfort: 'moderate', engagement: 85, styles: ['Luxury', 'Editorial', 'Minimal', 'Business', 'Professional'], tags: ['premium', 'elegant', 'sophisticated'], genders: ['male', 'female', 'neutral'], scenes: ['architecture', 'indoor', 'urban'], angles: ['eye_level'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.1, y: 0.82, z: -0.1 } : i === 2 ? { ...j, x: -0.12 } : i === 3 ? { ...j, x: 0.08 } : i === 6 ? { ...j, x: -0.15, y: 0.35 } : i === 7 ? { ...j, x: 0.15, y: 0.38 } : j) },
  { id: 'champagne_toast', name: 'Champagne Toast', category: 'luxury', description: 'Holding glass, elegant wrist, refined posture', difficulty: 'hard', comfort: 'moderate', engagement: 82, styles: ['Luxury', 'Wedding', 'Editorial', 'Vintage', 'Celebration'], tags: ['celebratory', 'elegant', 'refined'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'architecture'], angles: ['eye_level', 'high_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.02, y: 0.82 } : i === 4 ? { ...j, x: -0.15, y: 0.5, z: 0.05 } : i === 5 ? { ...j, x: 0.25, y: 0.5, z: 0.05 } : i === 6 ? { ...j, x: -0.18, y: 0.35, z: 0.08 } : i === 7 ? { ...j, x: 0.3, y: 0.4, z: 0.05 } : j) },

  // 5. COUPLE POSES
  { id: 'forehead_touch', name: 'Forehead Touch', category: 'couple', description: 'Foreheads together, intimate close-up', difficulty: 'easy', comfort: 'comfortable', engagement: 96, styles: ['Couple', 'Lovely', 'Romantic', 'Wedding', 'Viral', 'PinterestTrend'], tags: ['intimate', 'romantic', 'close'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'nature', 'sunset'], angles: ['eye_level'], joints: bj().map((j, i) => ({ ...j, y: j.y * 0.85 })) },
  { id: 'dip_kiss', name: 'Dramatic Dip Kiss', category: 'couple', description: 'One partner dipped, dramatic romantic kiss', difficulty: 'hard', comfort: 'moderate', engagement: 94, styles: ['Couple', 'Cinematic', 'Wedding', 'Viral', 'Dramatic'], tags: ['dramatic', 'romantic', 'passionate'], genders: ['male', 'female'], scenes: ['urban', 'architecture', 'beach'], angles: ['eye_level'], joints: bj().map((j, i) => i === 13 ? { ...j, x: 0.2, y: 0.15, z: -0.1 } : i === 15 ? { ...j, x: 0.2, y: 0, z: -0.15 } : i === 8 ? { ...j, x: 0.05, y: 0.4, z: -0.05 } : j) },
  { id: 'back_hug', name: 'Back Hug', category: 'couple', description: 'One partner hugging from behind, chin on shoulder', difficulty: 'easy', comfort: 'comfortable', engagement: 91, styles: ['Couple', 'Lovely', 'Natural', 'Wedding', 'Aesthetic'], tags: ['candid', 'loving', 'warm'], genders: ['male', 'female', 'neutral'], scenes: ['nature', 'urban', 'beach', 'sunset'], angles: ['eye_level'], joints: bj().map((j, i) => i === 0 ? { ...j, y: 0.82, z: -0.05 } : i === 14 ? { ...j, x: -0.04 } : i === 15 ? { ...j, x: 0.04 } : j) },
  { id: 'hand_hold_walk', name: 'Hand Hold Walk', category: 'couple', description: 'Walking hand in hand, candid moment', difficulty: 'easy', comfort: 'comfortable', engagement: 93, styles: ['Couple', 'Travel', 'Natural', 'Lovely', 'Adventure'], tags: ['candid', 'romantic', 'travel'], genders: ['male', 'female', 'neutral'], scenes: ['nature', 'beach', 'street', 'mountain'], angles: ['eye_level'], joints: bj().map((j, i) => i === 6 ? { ...j, x: -0.15, y: 0.3, z: 0.05 } : i === 7 ? { ...j, x: 0.08, y: 0.3, z: 0.05 } : i === 12 ? { ...j, x: -0.1, y: 0.18, z: 0.05 } : i === 13 ? { ...j, x: 0.1, y: 0.2, z: -0.05 } : j) },
  { id: 'whisper', name: 'The Whisper', category: 'couple', description: 'Whispering in ear, intimate candid', difficulty: 'easy', comfort: 'comfortable', engagement: 90, styles: ['Couple', 'Lovely', 'Wedding', 'InstagramTrend'], tags: ['intimate', 'candid', 'loving'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'nature', 'beach'], angles: ['eye_level'], joints: bj().map((j, i) => i === 0 ? { ...j, x: -0.05, y: 0.8, z: -0.05 } : i === 3 ? { ...j, x: 0.2, y: 0.6, z: 0.1 } : i === 7 ? { ...j, x: 0.15, y: 0.5, z: 0.15 } : j) },

  // 6. FAMILY POSES
  { id: 'family_pile', name: 'Family Pile', category: 'family', description: 'Family huddled together, joyful group', difficulty: 'easy', comfort: 'comfortable', engagement: 88, styles: ['Natural', 'Lovely', 'Bright', 'Lifestyle'], tags: ['family', 'group', 'joyful'], genders: ['male', 'female', 'neutral'], scenes: ['nature', 'indoor', 'beach'], angles: ['eye_level', 'high_angle'], joints: bj() },
  { id: 'piggyback', name: 'Piggyback Fun', category: 'family', description: 'One carrying another on back, playful', difficulty: 'medium', comfort: 'moderate', engagement: 85, styles: ['Adventure', 'Natural', 'Cute', 'Lifestyle'], tags: ['playful', 'fun', 'active'], genders: ['male', 'female'], scenes: ['nature', 'beach', 'park'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 14 ? { ...j, x: -0.1 } : i === 15 ? { ...j, x: 0.1 } : j) },

  // 7. SOLO POSES (expanded)
  { id: 'confident_solo', name: 'Confident Solo', category: 'solo', description: 'Standing tall, weight on one leg, arms at sides', difficulty: 'easy', comfort: 'comfortable', engagement: 85, styles: ['Natural', 'Aesthetic', 'Minimal', 'Bright'], tags: ['solo', 'confident', 'simple'], genders: ['male', 'female', 'neutral'], scenes: ['urban', 'architecture', 'nature'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 14 ? { ...j, x: -0.04 } : i === 15 ? { ...j, x: 0.12 } : j) },
  { id: 'thoughtful_solo', name: 'Thoughtful Solo', category: 'solo', description: 'Hand on chin, contemplative look', difficulty: 'easy', comfort: 'comfortable', engagement: 82, styles: ['Moody', 'Dark', 'Aesthetic', 'Editorial'], tags: ['contemplative', 'serious', 'deep'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'urban', 'architecture'], angles: ['eye_level', 'high_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.02, y: 0.78, z: -0.02 } : i === 4 ? { ...j, x: -0.1, y: 0.52, z: 0.08 } : i === 6 ? { ...j, x: -0.08, y: 0.45, z: 0.12 } : j) },

  // 8. STREET PHOTOGRAPHY
  { id: 'candid_crossing', name: 'Candid Crossing', category: 'street', description: 'Crossing street naturally, looking to side', difficulty: 'easy', comfort: 'comfortable', engagement: 86, styles: ['Street', 'Travel', 'Natural', 'Vintage', 'Retro'], tags: ['candid', 'urban', 'movement'], genders: ['male', 'female', 'neutral'], scenes: ['street', 'urban'], angles: ['eye_level', 'high_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.05, y: 0.8, z: -0.08 } : i === 6 ? { ...j, x: -0.18, y: 0.32 } : i === 7 ? { ...j, x: 0.2, y: 0.35 } : i === 12 ? { ...j, x: -0.08, y: 0.2, z: 0.05 } : j) },
  { id: 'leaning_graffiti', name: 'Leaning by Graffiti', category: 'street', description: 'Leaning against colorful wall or graffiti', difficulty: 'easy', comfort: 'comfortable', engagement: 84, styles: ['Street', 'Urban', 'Aesthetic', 'Creative', 'InstagramTrend'], tags: ['urban', 'colorful', 'edgy'], genders: ['male', 'female', 'neutral'], scenes: ['street', 'urban'], angles: ['eye_level'], joints: bj().map((j, i) => i === 8 ? { ...j, x: -0.05, y: 0.52, z: 0.05 } : i === 14 ? { ...j, x: -0.1 } : i === 6 ? { ...j, x: -0.2, y: 0.32, z: 0.05 } : j) },

  // 9-11. NATURE / BEACH / MOUNTAIN
  { id: 'mountain_summit', name: 'Mountain Summit Victory', category: 'mountain', description: 'Arms raised in victory, standing tall', difficulty: 'medium', comfort: 'moderate', engagement: 93, styles: ['Adventure', 'Travel', 'Hero', 'Cinematic', 'Viral'], tags: ['summit', 'victory', 'epic'], genders: ['male', 'female', 'neutral'], scenes: ['mountain', 'nature'], angles: ['low_angle', 'eye_level'], joints: bj().map((j, i) => i === 4 ? { ...j, x: -0.35, y: 0.55 } : i === 5 ? { ...j, x: 0.35, y: 0.55 } : i === 6 ? { ...j, x: -0.5, y: 0.4 } : i === 7 ? { ...j, x: 0.5, y: 0.4 } : j) },
  { id: 'beach_walk_silhouette', name: 'Beach Walk Silhouette', category: 'beach', description: 'Walking along shoreline at sunset', difficulty: 'easy', comfort: 'comfortable', engagement: 95, styles: ['Travel', 'Cinematic', 'Romantic', 'Sunset', 'Viral'], tags: ['sunset', 'silhouette', 'romantic'], genders: ['male', 'female', 'neutral'], scenes: ['beach', 'nature', 'sunset'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 6 ? { ...j, x: -0.2, y: 0.32 } : i === 7 ? { ...j, x: 0.2, y: 0.35 } : i === 12 ? { ...j, x: -0.1, y: 0.18 } : i === 13 ? { ...j, x: 0.12, y: 0.22 } : j) },
  { id: 'nature_embrace', name: 'Nature Embrace', category: 'nature', description: 'Arms wide, embracing the landscape', difficulty: 'easy', comfort: 'comfortable', engagement: 90, styles: ['Travel', 'Natural', 'Adventure', 'Aesthetic', 'PinterestTrend'], tags: ['nature', 'free', 'expansive'], genders: ['male', 'female', 'neutral'], scenes: ['nature', 'mountain', 'beach'], angles: ['eye_level', 'low_angle', 'bird_eye'], joints: bj().map((j, i) => i === 4 ? { ...j, x: -0.45, y: 0.58 } : i === 5 ? { ...j, x: 0.45, y: 0.58 } : i === 6 ? { ...j, x: -0.6, y: 0.45 } : i === 7 ? { ...j, x: 0.6, y: 0.45 } : j) },

  // 12. SUNSET POSES
  { id: 'sunset_silhouette', name: 'Sunset Silhouette', category: 'sunset', description: 'Standing against the setting sun', difficulty: 'easy', comfort: 'comfortable', engagement: 94, styles: ['Cinematic', 'Romantic', 'Sunset', 'Viral', 'Aesthetic'], tags: ['sunset', 'silhouette', 'golden_hour'], genders: ['male', 'female', 'neutral'], scenes: ['beach', 'nature', 'mountain', 'sunset'], angles: ['eye_level'], joints: bj().map((j, i) => i === 14 ? { ...j, x: -0.04 } : j) },
  { id: 'sunset_jump', name: 'Sunset Jump', category: 'sunset', description: 'Jumping against sunset sky', difficulty: 'medium', comfort: 'moderate', engagement: 91, styles: ['Adventure', 'Travel', 'Viral', 'InstagramTrend'], tags: ['sunset', 'action', 'joyful'], genders: ['male', 'female', 'neutral'], scenes: ['beach', 'nature', 'sunset'], angles: ['low_angle'], joints: bj().map((j, i) => i === 12 ? { ...j, x: -0.1, y: 0.3, z: 0.08 } : i === 13 ? { ...j, x: 0.1, y: 0.35, z: -0.05 } : i === 14 ? { ...j, x: -0.12, y: 0.2, z: 0.1 } : i === 15 ? { ...j, x: 0.12, y: 0.25, z: -0.08 } : { ...j, y: j.y + 0.1 }) },

  // 13. ROOFTOP POSES
  { id: 'rooftop_gaze', name: 'Rooftop Gaze', category: 'rooftop', description: 'Looking over city from height', difficulty: 'easy', comfort: 'comfortable', engagement: 88, styles: ['Cinematic', 'Moody', 'Urban', 'Aesthetic', 'Editorial'], tags: ['cityscape', 'height', 'urban'], genders: ['male', 'female', 'neutral'], scenes: ['urban', 'architecture'], angles: ['high_angle', 'eye_level'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.05, y: 0.82, z: -0.08 } : i === 14 ? { ...j, x: -0.04 } : j) },
  { id: 'rooftop_edge', name: 'Rooftop Edge', category: 'rooftop', description: 'Sitting on edge, legs dangling', difficulty: 'hard', comfort: 'strenuous', engagement: 86, styles: ['Cinematic', 'Adventure', 'Moody', 'Daring'], tags: ['height', 'daring', 'urban'], genders: ['male', 'female', 'neutral'], scenes: ['urban', 'architecture'], angles: ['high_angle', 'bird_eye'], joints: bj().map((j, i) => i === 12 ? { ...j, x: -0.12, y: 0.1, z: 0.15 } : i === 13 ? { ...j, x: 0.12, y: 0.1, z: 0.15 } : i === 9 ? { ...j, y: 0.2, z: 0.05 } : j) },

  // 14. CAFÉ POSES
  { id: 'coffee_moment', name: 'Coffee Moment', category: 'cafe', description: 'Holding coffee cup, casual café vibe', difficulty: 'easy', comfort: 'comfortable', engagement: 84, styles: ['Lifestyle', 'Aesthetic', 'Cute', 'Minimal', 'PinterestTrend'], tags: ['cafe', 'coffee', 'casual'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'urban'], angles: ['eye_level', 'high_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.02, y: 0.78 } : i === 6 ? { ...j, x: -0.15, y: 0.3, z: 0.05 } : i === 7 ? { ...j, x: 0.18, y: 0.35, z: 0.03 } : j) },
  { id: 'laptop_worker', name: 'Laptop Worker', category: 'cafe', description: 'Working on laptop, focused, natural', difficulty: 'easy', comfort: 'comfortable', engagement: 76, styles: ['Lifestyle', 'Business', 'Professional', 'Minimal'], tags: ['work', 'focused', 'indoor'], genders: ['male', 'female', 'neutral'], scenes: ['indoor'], angles: ['high_angle', 'eye_level'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0, y: 0.75, z: 0.05 } : i === 6 ? { ...j, x: -0.12, y: 0.28, z: 0.12 } : i === 7 ? { ...j, x: 0.12, y: 0.28, z: 0.12 } : j) },

  // 15-16. CAR / BIKE PHOTOGRAPHY
  { id: 'car_lean', name: 'Car Lean', category: 'car', description: 'Leaning against car, casual cool', difficulty: 'easy', comfort: 'comfortable', engagement: 87, styles: ['Luxury', 'Street', 'Aesthetic', 'Vintage', 'Retro'], tags: ['car', 'automotive', 'cool'], genders: ['male', 'female', 'neutral'], scenes: ['urban', 'street'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 8 ? { ...j, x: -0.05, y: 0.5, z: 0.05 } : i === 14 ? { ...j, x: -0.08 } : i === 6 ? { ...j, x: -0.22, y: 0.3, z: 0.05 } : i === 7 ? { ...j, x: 0.15, y: 0.35 } : j) },
  { id: 'bike_riding', name: 'Bike Riding', category: 'bike', description: 'Riding bicycle, motion capture', difficulty: 'medium', comfort: 'moderate', engagement: 82, styles: ['Adventure', 'Travel', 'Active', 'Natural'], tags: ['bike', 'cycling', 'motion'], genders: ['male', 'female', 'neutral'], scenes: ['nature', 'street', 'urban'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: -0.05, y: 0.78, z: 0.05 } : i === 6 ? { ...j, x: -0.2, y: 0.3, z: 0.1 } : i === 7 ? { ...j, x: 0.25, y: 0.32, z: -0.05 } : j) },

  // 17. DRONE INSPIRED POSES
  { id: 'starfish_topdown', name: 'Starfish Top-Down', category: 'drone', description: 'Lying on ground, arms and legs spread, overhead view', difficulty: 'easy', comfort: 'comfortable', engagement: 90, styles: ['Drone', 'Creative', 'Aesthetic', 'Viral', 'InstagramTrend'], tags: ['aerial', 'topdown', 'creative'], genders: ['male', 'female', 'neutral'], scenes: ['beach', 'nature', 'mountain'], angles: ['bird_eye', 'overhead'], joints: bj().map((j, i) => ({ ...j, y: j.y * 0.2, z: j.z - 0.1, x: i === 4 ? -0.35 : i === 5 ? 0.35 : i === 6 ? -0.45 : i === 7 ? 0.45 : i === 12 ? -0.15 : i === 13 ? 0.15 : j.x })) },
  { id: 'arrow_topdown', name: 'Arrow Formation', category: 'drone', description: 'Lying straight, arms tight, drone overhead', difficulty: 'easy', comfort: 'comfortable', engagement: 85, styles: ['Drone', 'Minimal', 'Creative'], tags: ['aerial', 'symmetry', 'minimal'], genders: ['male', 'female', 'neutral'], scenes: ['beach', 'nature'], angles: ['bird_eye', 'overhead'], joints: bj().map((j, i) => ({ ...j, y: j.y * 0.2, z: j.z - 0.15, x: i === 4 ? -0.02 : i === 5 ? 0.02 : i === 6 ? -0.02 : i === 7 ? 0.02 : i === 14 ? -0.02 : i === 15 ? 0.02 : j.x * 0.5 })) },
  { id: 'heart_topdown', name: 'Heart Formation', category: 'drone', description: 'Arms curved overhead forming heart, drone view', difficulty: 'hard', comfort: 'strenuous', engagement: 92, styles: ['Drone', 'Creative', 'Lovely', 'Viral', 'Couple'], tags: ['aerial', 'heart', 'romantic'], genders: ['male', 'female', 'neutral'], scenes: ['beach', 'nature'], angles: ['bird_eye', 'overhead'], joints: bj().map((j, i) => ({ ...j, y: j.y * 0.2, z: j.z - 0.1, x: i === 4 ? -0.25 : i === 5 ? 0.25 : i === 6 ? -0.15 : i === 7 ? 0.15 : j.x })) },

  // 18. FITNESS POSES
  { id: 'runner_start', name: 'Runner Start', category: 'fitness', description: 'Crouched starting position, explosive energy', difficulty: 'medium', comfort: 'strenuous', engagement: 80, styles: ['Fitness', 'Active', 'Hero', 'Dynamic'], tags: ['sports', 'action', 'dynamic'], genders: ['male', 'female', 'neutral'], scenes: ['nature', 'urban', 'beach'], angles: ['low_angle', 'eye_level'], joints: bj().map((j, i) => i === 12 ? { ...j, x: -0.2, y: 0.08, z: 0.05 } : i === 13 ? { ...j, x: 0.05, y: 0.15, z: -0.05 } : i === 14 ? { ...j, x: -0.25, y: 0, z: 0.1 } : i === 15 ? { ...j, x: 0.05, y: 0, z: -0.08 } : i === 9 ? { ...j, y: 0.15 } : j) },
  { id: 'yoga_tree', name: 'Tree Pose', category: 'fitness', description: 'Yoga tree pose, elegant balance', difficulty: 'hard', comfort: 'strenuous', engagement: 78, styles: ['Fitness', 'Aesthetic', 'Minimal', 'Natural'], tags: ['yoga', 'balance', 'wellness'], genders: ['male', 'female', 'neutral'], scenes: ['nature', 'beach', 'indoor'], angles: ['eye_level'], joints: bj().map((j, i) => i === 12 ? { ...j, x: 0, y: 0.15, z: -0.1 } : i === 14 ? { ...j, x: 0, y: 0, z: -0.05 } : i === 13 ? { ...j, x: 0.08, y: 0.35, z: 0 } : i === 6 ? { ...j, x: -0.25, y: 0.35, z: 0 } : i === 7 ? { ...j, x: 0.25, y: 0.35, z: 0 } : j) },

  // 19. LIFESTYLE POSES
  { id: 'morning_routine', name: 'Morning Routine', category: 'lifestyle', description: 'Natural morning moment, fresh and candid', difficulty: 'easy', comfort: 'comfortable', engagement: 83, styles: ['Lifestyle', 'Natural', 'Aesthetic', 'Bright', 'PinterestTrend'], tags: ['morning', 'casual', 'fresh'], genders: ['male', 'female', 'neutral'], scenes: ['indoor'], angles: ['eye_level', 'high_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.03, y: 0.78, z: 0.02 } : j) },
  { id: 'reading_corner', name: 'Reading Corner', category: 'lifestyle', description: 'Reading a book, cozy corner, natural light', difficulty: 'easy', comfort: 'comfortable', engagement: 81, styles: ['Lifestyle', 'Aesthetic', 'Vintage', 'Cozy', 'Minimal'], tags: ['reading', 'cozy', 'quiet'], genders: ['male', 'female', 'neutral'], scenes: ['indoor'], angles: ['eye_level', 'high_angle'], joints: bj().map((j, i) => i === 6 ? { ...j, x: -0.15, y: 0.28, z: 0.1 } : i === 7 ? { ...j, x: 0.2, y: 0.3, z: 0.08 } : i === 12 ? { ...j, x: -0.12, y: 0.12, z: 0.05 } : i === 13 ? { ...j, x: 0.12, y: 0.12, z: 0.05 } : j) },

  // 20. INFLUENCER POSES
  { id: 'flatlay_coffee', name: 'Coffee Flatlay', category: 'influencer', description: 'Top-down shot with coffee and phone', difficulty: 'easy', comfort: 'comfortable', engagement: 88, styles: ['InstagramTrend', 'PinterestTrend', 'Lifestyle', 'Aesthetic', 'Cute'], tags: ['flatlay', 'influencer', 'coffee'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'cafe'], angles: ['bird_eye', 'overhead'], joints: bj().map((j, i) => i === 6 ? { ...j, x: -0.1, y: 0.25, z: 0.05 } : i === 7 ? { ...j, x: 0.15, y: 0.25, z: 0.05 } : i === 0 ? { ...j, y: 0.7, z: 0.1 } : j) },
  { id: 'mirror_selfie', name: 'Mirror Selfie', category: 'influencer', description: 'Taking a selfie in mirror, phone covering part of face', difficulty: 'easy', comfort: 'comfortable', engagement: 90, styles: ['InstagramTrend', 'Viral', 'Fashion', 'Street', 'Aesthetic'], tags: ['selfie', 'mirror', 'influencer'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'urban'], angles: ['eye_level'], joints: bj().map((j, i) => i === 6 ? { ...j, x: -0.15, y: 0.35, z: 0.1 } : i === 7 ? { ...j, x: 0.25, y: 0.4, z: 0.08 } : j) },
  { id: 'outfit_of_day', name: 'Outfit of the Day', category: 'influencer', description: 'Full body outfit showcase, casual stance', difficulty: 'easy', comfort: 'comfortable', engagement: 87, styles: ['InstagramTrend', 'Fashion', 'Street', 'Aesthetic', 'PinterestTrend'], tags: ['outfit', 'fashion', 'style'], genders: ['male', 'female', 'neutral'], scenes: ['urban', 'indoor', 'street'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 6 ? { ...j, x: -0.18, y: 0.32, z: 0.02 } : i === 7 ? { ...j, x: 0.1, y: 0.35, z: -0.02 } : i === 14 ? { ...j, x: -0.04 } : i === 15 ? { ...j, x: 0.12 } : j) },

  // 21. WEDDING POSES
  { id: 'first_look', name: 'First Look', category: 'wedding', description: 'Groom seeing bride for first time, emotional', difficulty: 'medium', comfort: 'moderate', engagement: 97, styles: ['Wedding', 'Romantic', 'Cinematic', 'Lovely', 'Viral'], tags: ['wedding', 'emotional', 'first_look'], genders: ['male', 'female'], scenes: ['nature', 'indoor', 'architecture'], angles: ['eye_level'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.08, y: 0.82, z: -0.05 } : j) },
  { id: 'veil_shot', name: 'Veil Shot', category: 'wedding', description: 'Veil blowing in wind, ethereal bridal shot', difficulty: 'medium', comfort: 'moderate', engagement: 95, styles: ['Wedding', 'Cinematic', 'Aesthetic', 'Editorial', 'PinterestTrend'], tags: ['bridal', 'veil', 'ethereal'], genders: ['female'], scenes: ['nature', 'beach', 'architecture'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: -0.05, y: 0.85, z: -0.08 } : i === 6 ? { ...j, x: -0.2, y: 0.3, z: 0.05 } : i === 7 ? { ...j, x: 0.15, y: 0.35 } : j) },
  { id: 'ring_shot', name: 'Ring Detail Shot', category: 'wedding', description: 'Hands together, ring focused, shallow depth', difficulty: 'easy', comfort: 'comfortable', engagement: 93, styles: ['Wedding', 'Minimal', 'Aesthetic', 'Luxury'], tags: ['detail', 'ring', 'hands'], genders: ['male', 'female'], scenes: ['indoor', 'nature'], angles: ['eye_level', 'high_angle'], joints: bj().map((j, i) => i === 6 ? { ...j, x: -0.05, y: 0.3, z: 0.1 } : i === 7 ? { ...j, x: 0.05, y: 0.3, z: 0.1 } : j) },

  // 22. CINEMATIC HERO POSES
  { id: 'hero_walk', name: 'Hero Walk', category: 'cinematic_hero', description: 'Walking toward camera, epic slow-motion feel', difficulty: 'medium', comfort: 'moderate', engagement: 94, styles: ['Cinematic', 'Hero', 'Dramatic', 'Viral', 'Editorial'], tags: ['hero', 'epic', 'cinematic'], genders: ['male', 'female', 'neutral'], scenes: ['urban', 'architecture', 'mountain'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.02, y: 0.82 } : i === 6 ? { ...j, x: -0.22, y: 0.3, z: 0.08 } : i === 7 ? { ...j, x: 0.25, y: 0.32, z: -0.05 } : i === 12 ? { ...j, x: -0.12, y: 0.18, z: 0.08 } : i === 13 ? { ...j, x: 0.12, y: 0.22, z: -0.08 } : j) },
  { id: 'superhero_landing', name: 'Superhero Landing', category: 'cinematic_hero', description: 'One knee down, dramatic landing pose', difficulty: 'hard', comfort: 'strenuous', engagement: 91, styles: ['Cinematic', 'Hero', 'Dramatic', 'Creative', 'Dark'], tags: ['superhero', 'dramatic', 'powerful'], genders: ['male', 'female', 'neutral'], scenes: ['urban', 'architecture', 'mountain'], angles: ['low_angle', 'eye_level'], joints: bj().map((j, i) => i === 12 ? { ...j, x: -0.15, y: 0.05, z: 0.1 } : i === 14 ? { ...j, x: -0.15, y: 0, z: 0.15 } : i === 9 ? { ...j, y: 0.15 } : i === 6 ? { ...j, x: -0.25, y: 0.35, z: 0.05 } : i === 7 ? { ...j, x: 0.3, y: 0.3, z: -0.05 } : j) },
  { id: 'hero_profile', name: 'Hero Profile', category: 'cinematic_hero', description: 'Strong profile stance, looking into distance', difficulty: 'medium', comfort: 'moderate', engagement: 89, styles: ['Cinematic', 'Hero', 'Editorial', 'Moody', 'Dark'], tags: ['hero', 'profile', 'strong'], genders: ['male', 'female', 'neutral'], scenes: ['architecture', 'urban', 'mountain'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.12, y: 0.82, z: -0.12 } : i === 14 ? { ...j, x: -0.08 } : i === 15 ? { ...j, x: 0.08 } : i === 6 ? { ...j, x: -0.2, y: 0.32, z: 0.05 } : i === 7 ? { ...j, x: 0.15, y: 0.38 } : j) },

  // 23. EDITORIAL MAGAZINE POSES
  { id: 'magazine_cower', name: 'Magazine Cover Stare', category: 'editorial_magazine', description: 'Direct stare, strong eye contact, fashion-forward', difficulty: 'medium', comfort: 'moderate', engagement: 91, styles: ['Editorial', 'Fashion', 'Luxury', 'Dark', 'Moody'], tags: ['editorial', 'magazine', 'fierce'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'architecture', 'urban'], angles: ['eye_level'], joints: bj().map((j, i) => i === 2 ? { ...j, x: -0.18 } : i === 3 ? { ...j, x: 0.18 } : i === 6 ? { ...j, x: -0.2, y: 0.32 } : i === 7 ? { ...j, x: 0.2, y: 0.35, z: -0.05 } : j) },
  { id: 'editorial_lean', name: 'Editorial Lean', category: 'editorial_magazine', description: 'Leaning back, supported by hands, editorial cool', difficulty: 'medium', comfort: 'moderate', engagement: 88, styles: ['Editorial', 'Fashion', 'Aesthetic', 'Creative'], tags: ['editorial', 'editorial_fashion', 'cool'], genders: ['male', 'female', 'neutral'], scenes: ['architecture', 'urban', 'indoor'], angles: ['eye_level', 'low_angle'], joints: bj().map((j, i) => i === 8 ? { ...j, x: -0.03, y: 0.5, z: 0.08 } : i === 6 ? { ...j, x: -0.18, y: 0.4, z: 0.1 } : i === 7 ? { ...j, x: 0.22, y: 0.42, z: 0.05 } : i === 14 ? { ...j, x: -0.08 } : i === 15 ? { ...j, x: 0.08 } : j) },
  { id: 'editorial_dynamic', name: 'Editorial Dynamic', category: 'editorial_magazine', description: 'Dynamic body angle, asymmetrical pose, avant-garde', difficulty: 'hard', comfort: 'strenuous', engagement: 87, styles: ['Editorial', 'Fashion', 'Creative', 'Dark', 'AvantGarde'], tags: ['editorial', 'dynamic', 'avant_garde'], genders: ['female', 'neutral'], scenes: ['architecture', 'indoor'], angles: ['eye_level', 'low_angle', 'dutch_angle'], joints: bj().map((j, i) => i === 0 ? { ...j, x: -0.08, y: 0.8, z: 0.05 } : i === 2 ? { ...j, x: -0.2 } : i === 4 ? { ...j, x: -0.28, y: 0.45 } : i === 6 ? { ...j, x: -0.15, y: 0.3 } : i === 7 ? { ...j, x: 0.3, y: 0.35, z: -0.08 } : i === 14 ? { ...j, x: -0.12 } : i === 15 ? { ...j, x: 0.08 } : j) },

  // 24. BUSINESS PROFESSIONAL POSES
  { id: 'executive_stand', name: 'Executive Stand', category: 'business_professional', description: 'Confident executive posture, hands clasped', difficulty: 'easy', comfort: 'comfortable', engagement: 82, styles: ['Business', 'Professional', 'Minimal', 'Corporate'], tags: ['executive', 'confident', 'professional'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'architecture', 'office'], angles: ['eye_level'], joints: bj().map((j, i) => i === 4 ? { ...j, x: -0.1, y: 0.52, z: 0.05 } : i === 5 ? { ...j, x: 0.1, y: 0.52, z: 0.05 } : i === 6 ? { ...j, x: -0.08, y: 0.38, z: 0.08 } : i === 7 ? { ...j, x: 0.08, y: 0.38, z: 0.08 } : j) },
  { id: 'boardroom_walk', name: 'Boardroom Walk', category: 'business_professional', description: 'Walking with purpose, professional attire', difficulty: 'easy', comfort: 'comfortable', engagement: 80, styles: ['Business', 'Professional', 'Corporate', 'Minimal'], tags: ['professional', 'walk', 'corporate'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'architecture', 'office'], angles: ['eye_level'], joints: bj().map((j, i) => i === 6 ? { ...j, x: -0.18, y: 0.3 } : i === 7 ? { ...j, x: 0.2, y: 0.32 } : i === 12 ? { ...j, x: -0.08, y: 0.18 } : i === 13 ? { ...j, x: 0.1, y: 0.22 } : j) },
  { id: 'headshot_classic', name: 'Classic Headshot', category: 'business_professional', description: 'Professional headshot, clean background', difficulty: 'easy', comfort: 'comfortable', engagement: 85, styles: ['Professional', 'Business', 'Minimal', 'Corporate', 'LinkedIn'], tags: ['headshot', 'professional', 'clean'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'office'], angles: ['eye_level'], joints: bj().map((j, i) => i === 0 ? { ...j, x: 0.02, y: 0.82 } : i === 6 ? { ...j, x: -0.15, y: 0.35, z: 0.05 } : i === 7 ? { ...j, x: 0.12, y: 0.35, z: 0.05 } : j) },
  { id: 'confident_arms', name: 'Confident Arms Crossed', category: 'business_professional', description: 'Arms crossed, confident, approachable', difficulty: 'easy', comfort: 'comfortable', engagement: 83, styles: ['Professional', 'Business', 'Corporate', 'Minimal'], tags: ['confident', 'crossed_arms', 'professional'], genders: ['male', 'female', 'neutral'], scenes: ['indoor', 'architecture', 'office'], angles: ['eye_level'], joints: bj().map((j, i) => i === 4 ? { ...j, x: -0.12, y: 0.52, z: 0.08 } : i === 5 ? { ...j, x: 0.12, y: 0.52, z: 0.08 } : i === 6 ? { ...j, x: -0.1, y: 0.4, z: 0.12 } : i === 7 ? { ...j, x: 0.1, y: 0.4, z: 0.12 } : j) },
];

export function getPosesByStyle(style: StyleTab): PunkPose[] {
  return ALL_POSES.filter(p => p.styles.includes(style));
}

export function getPosesByCategory(category: string): PunkPose[] {
  return ALL_POSES.filter(p => p.category === category || p.category.includes(category));
}

export const STYLE_TABS: StyleTab[] = [
  'Aesthetic', 'Cinematic', 'Lovely', 'Natural', 'Travel',
  'Street', 'Luxury', 'Fashion', 'Editorial', 'Hero',
  'Minimal', 'Cute', 'Adventure', 'Creative', 'Drone',
  'Couple', 'Wedding', 'InstagramTrend', 'PinterestTrend',
  'Viral', 'Vintage', 'Retro', 'Moody', 'Dark',
  'Bright', 'Professional', 'Business', 'Fitness',
];

export const CATEGORY_NAMES: Record<string, string> = {
  portrait: 'Portrait Poses', travel: 'Travel Poses', fashion: 'Fashion Poses',
  luxury: 'Luxury Poses', couple: 'Couple Poses', family: 'Family Poses',
  solo: 'Solo Poses', street: 'Street Photography', nature: 'Nature Poses',
  beach: 'Beach Poses', mountain: 'Mountain Poses', sunset: 'Sunset Poses',
  rooftop: 'Rooftop Poses', cafe: 'Café Poses', car: 'Car Photography',
  bike: 'Bike Photography', drone: 'Drone Inspired', fitness: 'Fitness Poses',
  lifestyle: 'Lifestyle Poses', influencer: 'Influencer Poses',
  wedding: 'Wedding Poses', cinematic_hero: 'Cinematic Hero',
  editorial_magazine: 'Editorial Magazine', business_professional: 'Business Professional',
};
