import type { LUTPreset } from '../../lib/types';

export const LUT_PRESETS: LUTPreset[] = [
  {
    id: 'revenant',
    name: 'Revenant',
    inspiredBy: 'The Revenant (2015)',
    tone: 'Cold steel blue, desaturated shadows',
    intensity: 0.8,
    colors: {
      shadows: [0.05, 0.08, 0.15],
      mids: [0.5, 0.55, 0.65],
      highlights: [0.9, 0.92, 1.0],
      saturation: 0.6,
      contrast: 1.3,
      temperature: 5500,
      tint: -10,
    },
  },
  {
    id: 'everest',
    name: 'Everest',
    inspiredBy: 'Everest cinematography',
    tone: 'Ice white highlights, cyan mids',
    intensity: 0.85,
    colors: {
      shadows: [0.1, 0.15, 0.2],
      mids: [0.6, 0.7, 0.8],
      highlights: [0.95, 0.98, 1.0],
      saturation: 0.7,
      contrast: 1.2,
      temperature: 6500,
      tint: -15,
    },
  },
  {
    id: 'hollywood',
    name: 'Hollywood',
    inspiredBy: 'Teal-orange blockbuster',
    tone: 'Teal shadows, orange skin tones',
    intensity: 0.9,
    colors: {
      shadows: [0.0, 0.1, 0.15],
      mids: [0.6, 0.5, 0.4],
      highlights: [1.0, 0.85, 0.7],
      saturation: 1.2,
      contrast: 1.4,
      temperature: 4800,
      tint: 5,
    },
  },
  {
    id: 'fuji_xpro',
    name: 'Fuji X-Pro',
    inspiredBy: 'Fuji film stock',
    tone: 'Warm greens, lifted shadows',
    intensity: 0.75,
    colors: {
      shadows: [0.15, 0.12, 0.08],
      mids: [0.5, 0.48, 0.4],
      highlights: [0.92, 0.9, 0.85],
      saturation: 1.1,
      contrast: 1.15,
      temperature: 5200,
      tint: 3,
    },
  },
  {
    id: 'kodak_vision',
    name: 'Kodak Vision',
    inspiredBy: 'Kodak 500T',
    tone: 'Rich reds, golden warmth',
    intensity: 0.85,
    colors: {
      shadows: [0.12, 0.05, 0.03],
      mids: [0.55, 0.4, 0.3],
      highlights: [0.95, 0.8, 0.65],
      saturation: 1.0,
      contrast: 1.25,
      temperature: 4500,
      tint: 8,
    },
  },
  {
    id: 'snapchat_vivid',
    name: 'Snapchat Vivid',
    inspiredBy: 'Snapchat pop',
    tone: 'High saturation, lifted blacks',
    intensity: 0.7,
    colors: {
      shadows: [0.1, 0.08, 0.1],
      mids: [0.55, 0.5, 0.55],
      highlights: [0.95, 0.92, 0.95],
      saturation: 1.5,
      contrast: 1.1,
      temperature: 5000,
      tint: 0,
    },
  },
  {
    id: 'golden_hour',
    name: 'Golden Hour',
    inspiredBy: 'Magic hour',
    tone: 'Warm amber, soft contrast',
    intensity: 0.9,
    colors: {
      shadows: [0.2, 0.1, 0.02],
      mids: [0.6, 0.45, 0.2],
      highlights: [0.95, 0.8, 0.5],
      saturation: 1.0,
      contrast: 1.1,
      temperature: 3800,
      tint: 12,
    },
  },
  {
    id: 'blue_hour',
    name: 'Blue Hour',
    inspiredBy: 'Twilight photography',
    tone: 'Cool blue, deep shadows',
    intensity: 0.85,
    colors: {
      shadows: [0.02, 0.05, 0.15],
      mids: [0.3, 0.4, 0.6],
      highlights: [0.7, 0.8, 1.0],
      saturation: 0.8,
      contrast: 1.3,
      temperature: 7500,
      tint: -20,
    },
  },
  {
    id: 'moody_bw',
    name: 'Moody B&W',
    inspiredBy: 'Classic monochrome',
    tone: 'High contrast silver tone',
    intensity: 1.0,
    colors: {
      shadows: [0.05, 0.05, 0.05],
      mids: [0.5, 0.5, 0.5],
      highlights: [0.95, 0.95, 0.95],
      saturation: 0.0,
      contrast: 1.6,
      temperature: 5500,
      tint: 0,
    },
  },
  {
    id: 'soft_matte',
    name: 'Soft Matte',
    inspiredBy: 'Instagram aesthetic',
    tone: 'Faded blacks, soft pastels',
    intensity: 0.65,
    colors: {
      shadows: [0.2, 0.18, 0.2],
      mids: [0.55, 0.52, 0.55],
      highlights: [0.9, 0.88, 0.9],
      saturation: 0.8,
      contrast: 0.9,
      temperature: 5200,
      tint: 2,
    },
  },
  {
    id: 'desert_dune',
    name: 'Desert Dune',
    inspiredBy: 'Middle East landscapes',
    tone: 'Warm sand, crushed shadows',
    intensity: 0.8,
    colors: {
      shadows: [0.15, 0.1, 0.05],
      mids: [0.55, 0.45, 0.3],
      highlights: [0.9, 0.8, 0.6],
      saturation: 0.9,
      contrast: 1.2,
      temperature: 4200,
      tint: 10,
    },
  },
  {
    id: 'arctic',
    name: 'Arctic',
    inspiredBy: 'Scandinavia look',
    tone: 'Cold whites, teal cast',
    intensity: 0.8,
    colors: {
      shadows: [0.05, 0.1, 0.2],
      mids: [0.5, 0.6, 0.75],
      highlights: [0.9, 0.95, 1.0],
      saturation: 0.7,
      contrast: 1.15,
      temperature: 7000,
      tint: -12,
    },
  },
  {
    id: 'anamorphic',
    name: 'Anamorphic',
    inspiredBy: 'Cinema lens look',
    tone: 'Horizontal lens flare overlay',
    intensity: 0.7,
    colors: {
      shadows: [0.08, 0.08, 0.12],
      mids: [0.5, 0.48, 0.55],
      highlights: [0.9, 0.88, 0.95],
      saturation: 0.9,
      contrast: 1.3,
      temperature: 5500,
      tint: -5,
    },
  },
  {
    id: 'neon_tokyo',
    name: 'Neon Tokyo',
    inspiredBy: 'Cyberpunk cities',
    tone: 'Pink/cyan high contrast',
    intensity: 0.9,
    colors: {
      shadows: [0.02, 0.0, 0.08],
      mids: [0.5, 0.3, 0.5],
      highlights: [0.95, 0.7, 0.9],
      saturation: 1.4,
      contrast: 1.5,
      temperature: 5000,
      tint: 15,
    },
  },
  {
    id: 'raw_natural',
    name: 'Raw Natural',
    inspiredBy: 'No LUT',
    tone: 'Flat, ungraded baseline',
    intensity: 0.0,
    colors: {
      shadows: [0.0, 0.0, 0.0],
      mids: [0.5, 0.5, 0.5],
      highlights: [1.0, 1.0, 1.0],
      saturation: 1.0,
      contrast: 1.0,
      temperature: 5500,
      tint: 0,
    },
  },
];

export function getLUTById(id: string): LUTPreset | undefined {
  return LUT_PRESETS.find((lut) => lut.id === id);
}
